# Site settings
title: SALabs_
email: ismo.aro@siili.com
description: > # this means to ignore newlines until "baseurl:"
  Our mission is to find new services and solutions around Software Automation, experiment them and distill them into saleable concepts, products and services.
baseurl:
url: https://salabs.github.io
twitter_username: salabs_
github_username:  salabs
linkedin_username: salabs
markdown: kramdown
highlighter: rouge
paginate: 15
paginate_path: "/blog/page:num/"
collections:
  projects:
    output: true
    permalink: /projects/:path/


